### ISSUE TITLE
Internal Error, player ID 2 didn't move but still moving.

### ISSUE THREAD

**Issue by Mathieu-R** [Julien00859/Bomberman#4]
Le personnage ne bouge pas correctement lors d'un déplacement.

2016/08/01 11:48:01 [WARNING] <game.bomberman> Game ID 1: Internal Error, player ID 2 didn't move but still moving.

**Comment by Julien00859** [comment]
2016/08/01 11:47:58 [DEBUG] <server.web_server> Message from client ID 1: {"cmd":"event","event":"move","kwargs":{"direction":"E"}}
	2016/08/01 11:47:58 [DEBUG] <server.game_manager> Player ID 1 fired event "move" to Game ID 1
	2016/08/01 11:47:58 [DEBUG] <game.bomberman> Game ID 1: Player ID 1 moved from [1.5, 1.5] to [1.6, 1.5]
	2016/08/01 11:47:58 [DEBUG] <game.bomberman> Game ID 1: Player ID 1 moved from [1.6, 1.5] to [1.7, 1.5]
	2016/08/01 11:47:59 [DEBUG] <game.bomberman> Game ID 1: Player ID 1 moved from [1.7, 1.5] to [1.8, 1.5]
	2016/08/01 11:47:59 [DEBUG] <game.bomberman> Game ID 1: Player ID 1 moved from [1.8, 1.5] to [1.9, 1.5]
	2016/08/01 11:47:59 [DEBUG] <game.bomberman> Game ID 1: Player ID 1 moved from [1.9, 1.5] to [2.0, 1.5]
	2016/08/01 11:47:59 [DEBUG] <game.bomberman> Game ID 1: Player ID 1 moved from [2.0, 1.5] to [2.1, 1.5]
	2016/08/01 11:47:59 [WARNING] <game.bomberman> Game ID 1: Internal Error, player ID 1 didn't move but still moving.
